// /**
//  * AI-Generated Content Analyzer
//  * Determines if content was likely generated by AI
//  * Browser-agnostic module
//  */

// /**
//  * Analyze content for AI generation indicators
//  * @param {Object} chunk - Content chunk with text and metadata
//  * @param {Object} pageMetadata - Page-level metadata
//  * @param {Object} options - Analysis options
//  * @returns {Promise<Object>} Analysis results
//  */
// export async function analyzeAIGenerated(chunk, pageMetadata = {}, options = {}) {
//   const {
//     mode = 'local',
//     config = {}
//   } = options;

//   const text = chunk.text || '';
//   const combinedContext = {
//     text,
//     url: pageMetadata.url || '',
//     domain: pageMetadata.domain || '',
//     title: pageMetadata.title || ''
//   };

//   switch (mode) {
//     case 'local':
//       return await analyzeWithLocalModel(combinedContext, config);
//     case 'openai':
//       return await analyzeWithOpenAI(combinedContext, config);
//     case 'anthropic':
//       return await analyzeWithAnthropic(combinedContext, config);
//     default:
//       return getMockResults(combinedContext);
//   }
// }

// async function analyzeWithLocalModel(context, config) {
//   return analyzeWithHeuristics(context);
// }

// async function analyzeWithOpenAI(context, config) {
//   if (!config.apiKey) {
//     return getMockResults(context);
//   }

//   try {
//     const response = await fetch('https://api.openai.com/v1/chat/completions', {
//       method: 'POST',
//       headers: {
//         'Authorization': `Bearer ${config.apiKey}`,
//         'Content-Type': 'application/json'
//       },
//       body: JSON.stringify({
//         model: config.model || 'gpt-4',
//         messages: [
//           {
//             role: 'system',
//             content: getSystemPrompt()
//           },
//           {
//             role: 'user',
//             content: formatContextForPrompt(context)
//           }
//         ],
//         temperature: 0.3
//       })
//     });

//     if (!response.ok) {
//       throw new Error(`OpenAI API error: ${response.statusText}`);
//     }

//     const data = await response.json();
//     return parseAIResponse(data.choices[0]?.message?.content || '');
//   } catch (error) {
//     console.error('OpenAI analysis error:', error);
//     return analyzeWithHeuristics(context);
//   }
// }

// async function analyzeWithAnthropic(context, config) {
//   if (!config.apiKey) {
//     return getMockResults(context);
//   }

//   try {
//     const response = await fetch('https://api.anthropic.com/v1/messages', {
//       method: 'POST',
//       headers: {
//         'x-api-key': config.apiKey,
//         'anthropic-version': '2023-06-01',
//         'Content-Type': 'application/json'
//       },
//       body: JSON.stringify({
//         model: config.model || 'claude-3-opus-20240229',
//         max_tokens: 1024,
//         messages: [
//           {
//             role: 'user',
//             content: `${getSystemPrompt()}\n\n${formatContextForPrompt(context)}`
//           }
//         ]
//       })
//     });

//     if (!response.ok) {
//       throw new Error(`Anthropic API error: ${response.statusText}`);
//     }

//     const data = await response.json();
//     return parseAIResponse(data.content[0]?.text || '');
//   } catch (error) {
//     console.error('Anthropic analysis error:', error);
//     return analyzeWithHeuristics(context);
//   }
// }

// function analyzeWithHeuristics(context) {
//   const text = context.text;
//   let score = 0;
//   const flags = [];

//   // Check for repetitive sentence structures
//   const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 10);
//   if (sentences.length > 3) {
//     const firstWords = sentences.map(s => {
//       const words = s.trim().split(/\s+/);
//       return words.length > 0 ? words[0].toLowerCase() : '';
//     });
//     const uniqueStarts = new Set(firstWords).size;
//     const repetitionRatio = 1 - (uniqueStarts / sentences.length);
//     if (repetitionRatio > 0.4) {
//       score += 0.2;
//       flags.push('repetitive_structure');
//     }
//   }

//   // Check for overly formal or generic language
//   const genericPhrases = [
//     'it is important to note',
//     'in conclusion',
//     'it should be noted',
//     'furthermore',
//     'moreover',
//     'additionally',
//     'as a result',
//     'in summary'
//   ];
//   const genericCount = genericPhrases.filter(phrase => 
//     text.toLowerCase().includes(phrase)
//   ).length;
//   if (genericCount > sentences.length * 0.3 && sentences.length > 5) {
//     score += 0.15;
//     flags.push('generic_language');
//   }

//   // Check for lack of personal pronouns or informal language
//   const personalPronouns = ['i', 'we', 'my', 'our', 'me', 'us'];
//   const hasPersonalPronouns = personalPronouns.some(pronoun => 
//     new RegExp(`\\b${pronoun}\\b`, 'i').test(text)
//   );
//   if (!hasPersonalPronouns && text.length > 500) {
//     score += 0.1;
//     flags.push('lack_of_personal_voice');
//   }

//   // Check for overly perfect grammar (AI often has perfect grammar)
//   // This is harder to detect, but very few typos + perfect structure can be indicator
//   const commonTypos = ['teh', 'adn', 'taht', 'recieve'];
//   const typoCount = commonTypos.filter(typo => text.toLowerCase().includes(typo)).length;
//   // Very low typos with high generic language score might indicate AI
//   if (typoCount === 0 && genericCount > 3 && text.length > 300) {
//     score += 0.1;
//     flags.push('overly_perfect_grammar');
//   }

//   // Check for unusual word patterns
//   // AI often uses certain transition words more frequently
//   const transitionWords = ['however', 'therefore', 'moreover', 'furthermore', 'consequently'];
//   const transitionCount = transitionWords.filter(word => 
//     new RegExp(`\\b${word}\\b`, 'i').test(text)
//   ).length;
//   if (transitionCount > sentences.length * 0.2 && sentences.length > 5) {
//     score += 0.15;
//     flags.push('excessive_transitions');
//   }

//   // Check for lack of specific details or examples
//   // AI content often lacks concrete specifics
//   const specificIndicators = [
//     /\d{4}/, // Years
//     /\$\d+/, // Money
//     /[A-Z]{2,}/, // Acronyms
//     /@\w+/, // Mentions
//     /#\w+/ // Hashtags
//   ];
//   const specificCount = specificIndicators.filter(regex => regex.test(text)).length;
//   if (specificCount === 0 && text.length > 500) {
//     score += 0.1;
//     flags.push('lack_of_specific_details');
//   }

//   return {
//     score: Math.min(score, 1.0),
//     confidence: 0.55,
//     flags,
//     explanation: generateExplanation(score, flags)
//   };
// }

// function getSystemPrompt() {
//   return `You are a content authenticity expert. Determine if the following content was likely generated by AI.

// Consider:
// - Repetitive sentence structures or patterns
// - Overly formal or generic language
// - Lack of personal voice or informal elements
// - Perfect grammar with no typos (unusual for human writing)
// - Excessive use of transition words
// - Lack of specific details, examples, or personal anecdotes
// - Unusual word choice patterns
// - Overall "too perfect" or formulaic structure

// Respond with a JSON object containing:
// - score: float between 0 (likely human-written) and 1 (likely AI-generated)
// - confidence: float between 0 and 1
// - flags: array of specific AI generation indicators
// - explanation: brief explanation of findings`;
// }

// function formatContextForPrompt(context) {
//   return `URL: ${context.url || 'N/A'}
// Domain: ${context.domain || 'N/A'}
// Title: ${context.title || 'N/A'}

// Content:
// ${context.text}`;
// }

// function parseAIResponse(responseText) {
//   try {
//     const jsonMatch = responseText.match(/\{[\s\S]*\}/);
//     if (jsonMatch) {
//       const parsed = JSON.parse(jsonMatch[0]);
//       return {
//         score: Math.max(0, Math.min(1, parsed.score || 0)),
//         confidence: Math.max(0, Math.min(1, parsed.confidence || 0.7)),
//         flags: parsed.flags || [],
//         explanation: parsed.explanation || 'Analysis completed'
//       };
//     }
//   } catch (e) {
//     // Fallback parsing
//   }

//   const scoreMatch = responseText.match(/score[:\s]+([\d.]+)/i);
//   const score = scoreMatch ? parseFloat(scoreMatch[1]) : 0.1;

//   return {
//     score: Math.max(0, Math.min(1, score)),
//     confidence: 0.5,
//     flags: [],
//     explanation: responseText.substring(0, 200)
//   };
// }

// function generateExplanation(score, flags) {
//   if (score < 0.2) {
//     return 'Content appears to be human-written with natural characteristics.';
//   } else if (score < 0.5) {
//     return `Some AI generation indicators detected: ${flags.join(', ')}.`;
//   } else {
//     return `Multiple AI generation indicators detected: ${flags.join(', ')}. High likelihood of AI-generated content.`;
//   }
// }

// function getMockResults(context) {
//   return {
//     score: 0.10 + Math.random() * 0.15,
//     confidence: 0.70 + Math.random() * 0.2,
//     flags: [],
//     explanation: 'Mock analysis for AI generation detection'
//   };
// }

